### ISSUE TITLE
Error on Full Refresh - Failure to match models

### ISSUE THREAD

**Issue by konosp** [Tomme/dbt-athena#22]
When trying to run dbt with full refresh, i receive the below error. Have never seen this before so I am not sure this if is a setup issue on my side or something else.

![dbt-error](https://user-images.githubusercontent.com/18295722/121031517-51723280-c7a2-11eb-9796-78d98acb996b.png)

Any thoughts?

**Comment by sujeetpillai** [comment]
I had the same issue and debugged it down to this line in dbt. 
https://github.com/dbt-labs/dbt/blob/e5c63884e201c16bf8c905ecf5672e176111d65d/core/dbt/adapters/base/relation.py#L35

In my profiles.yml I had set 
database: AwsDataCatalog

In the above mentioned line where it was comparing the database it was comparing a lowercase 'awsdatacatalog' with 'AwsDataCatalog'

Setting the database value in profiles.yml to lowercase awsdatacatalog solved it for me.

**Comment by konosp** [comment]
Hi @sujeetpillai,

Thanks for this! Seems to have solved my issue. dbt now works great.
Closing the ticket.

Cheers
