### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by smitthakkar1** [Tomme/dbt-athena#25]
I am relatively new to DBT and trying my hands on `dbt-athena`. I am trying to use it with my exiting DBT repo. Can I do it ? 
Can I add `dbt-athena` into my `requirements.txt` ? Is there any example of some repo which is using `dbt-athena`?

Thanks

**Comment by Tomme** [comment]
Hey @smitthakkar1,

* You can use the adapter with an existing dbt repository, though it is highly likely you will need to update your `sources` (to account for changes to table names) and there is also a good chance some of your SQL code may not directly compatible with Athena / Presto SQL, this will depends on what database you were utilising before.
* This repository is not currently on PyPi but you can use `pip` to directly install from GibHub. Simply add `git+https://github.com/Tomme/dbt-athena.git` to your `requirements.txt`
* I am not aware of any `dbt-athena` specific example repositories that are publicly accessible however they will be 99% the same as a typical dbt project. _After you account for feature limitations, e.g. no snapshots_

**Comment by smitthakkar1** [comment]
Thanks @Tomme for the answer !
