### ISSUE TITLE
Tables not cleaned up if materialized = table and static external location

### ISSUE THREAD

**Issue by ojaved-equip** [Tomme/dbt-athena#54]
Looks like issue was caused by this merge: https://github.com/Tomme/dbt-athena/pull/43

If we have a static external location and materialized = table (for full overwrite), the prior data in the external location is not cleaned up.

**Comment by courentin** [comment]
Thank you for this issue, I'm having the same error, I think https://github.com/Tomme/dbt-athena/pull/49 is fixing this issue

**Comment by nialloriordan** [comment]
@courentin @ojaved-equip I have created a new PR #72 that fixes this issue.

Thank you to [@datalytics1](https://github.com/datalytics1) for the original PR
