### ISSUE TITLE
relax boto3 version requirements

### ISSUE THREAD

**Issue by jankatins** [Tomme/dbt-athena#65]
The boto3 version requirement currently means you have to use an old version of the awscli if you install both into the same venv. That in turn means that aws sso does not work properly. It would be nice if the install requirement in setup.py could be changed to `>=` to allow installing higher versions and assume that higher versions are not breaking API (until proven otherwise...). 

E.g. 

```py
    install_requires=[
        "dbt-core>=1.0",
        "pyathena>=2.2.0",
        "boto3>=1.18.12",
        "tenacity>=6.3.1",
    ]
```

It's then up to the user to ensure that the installed versions produce a working set of packages.

**Comment by cgomez238** [comment]
I would like to emphasize this request as I am having issues using the dagster-aws library. There seems to be a bug in boto3 1.18.12 that conflicts with this library, and I am having a hard time finding a workaround.

**Comment by ConstantinoSchillebeeckx** [comment]
Adding another voice to the pile; looks like the last installable version of awswrangler is `2.12.1`

**Comment by ConstantinoSchillebeeckx** [comment]
@Tomme this issue can now be closed; thank you!
