### ISSUE TITLE
[enhancement] There is no support for using IAM role for authentication

### ISSUE THREAD

**Issue by ShantanuKumar** [Tomme/dbt-athena#98]
Currently you can only use `aws_profile_name` for authentication. The connection to athena is managed using pyathena which does support using iam role.

**Comment by ShantanuKumar** [comment]
This works depending if you use assume role functionality. You don't need to set `aws_profile_name`.

**Comment by Ryno-Marx** [comment]
@ShantanuKumar I'm sitting with this type of issue now.  Can you please elaborate what you mean by:

> This works depending if you use assume role functionality. You don't need to set aws_profile_name
